### ISSUE TITLE
Installation bug: missing requirements.txt

### ISSUE THREAD

**Issue by mvg256** [shapelets/timeseries-workshop#1]
Can't build a container from the Dockerfile. It seems that requirements.txt is missing.
When I run
```bash
docker build --rm -t shapelets/timeseries-workshop .
```
I get the following error at Step 17/18:
```
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by otorreno** [comment]
I have just uploaded the requirements.txt file. Give it another try.

**Comment by mvg256** [comment]
It works. Thank you!
